### ISSUE TITLE
can not install with truffle-hdwallet-provider installed

### ISSUE THREAD

**Issue by SvenMeyer** [rkalis/truffle-assertions#28] opened 2019-07-19 08:32 UTC
**Describe the bug**

install fails if truffle-hdwallet-provider is already installed

```
$ npm install truffle-hdwallet-provider@1.0.12
$ npm install npm install truffle-assertions

npm ERR! path /home/sum/DEV/test_HDWalletProvider_nonce/node_modules/web3-providers-ws/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /home/sum/DEV/test_HDWalletProvider_nonce/node_modules/web3-providers-ws/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /home/sum/DEV/test_HDWalletProvider_nonce/node_modules/web3-providers-ws/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sum/.npm/_logs/2019-07-19T08_24_41_215Z-debug.log
```

**Example test code**
```
$ npm install truffle-hdwallet-provider@1.0.12
$ npm install npm install truffle-assertions
```

**Expected behavior**
no error

**Environment Information**
Truffle v5.0.27 (core: 5.0.27)
Node v10.16.0
truffle-hdwallet-provider@1.0.12

[2019-07-19T08_24_41_215Z-debug.log](https://github.com/rkalis/truffle-assertions/files/3410183/2019-07-19T08_24_41_215Z-debug.log)

**Comment by rkalis** [comment] 2019-07-25 01:19
I see you closed the linked issue, does that mean this issue has been resolved?

**Comment by SvenMeyer** [comment] 2019-07-25 05:24
When I tried to reproduced the problem once I had posted it as an issue nere on github, the error did not show up any more, so I closed the issue. When I later tried again, the error show up again, but I had no time to further investigate what might have caused it to show up again.
Feel free to download the code and run it, should only take a minute ...

**Comment by rkalis** [comment] 2019-09-09 10:14
I'm not able to reproduce this using your environment:
Truffle v5.0.27 (core: 5.0.27)
Node v10.16.0
truffle-hdwallet-provider@1.0.12

Is this still an issue for you that you're able to reproduce across multiple projects?

**Comment by SvenMeyer** [comment] 2019-09-09 10:49
Looks ok to me now as well ...

**Comment by rkalis** [comment] 2019-09-09 10:51
Strange, these kinds of bugs. Closing the issue for now, but let me know if it persists later.

**Closed as completed by rkalis** 2019-09-09 10:51 UTC
